import { NextResponse } from "next/server";
import { getAdmin } from "@/lib/firebase-admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/* GET /api/match-odds — public cache of REAL 1X2 betting odds (footballdata.io).
 * Returns { [matchId]: { home, draw, away, updatedAt } }.
 * Generated by /api/cron/sync-odds; this endpoint only reads the cache.
 * Matches with no priced odds yet are simply absent from the response. */
export async function GET() {
  try {
    const { db } = getAdmin();
    const snap = await db.collection("live_data").doc("match_odds").get();
    return NextResponse.json(snap.exists ? (snap.data() || {}) : {});
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
