import { NextResponse } from "next/server";
import { getAdmin } from "@/lib/firebase-admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/* GET /api/match-summaries — public cache of AI-generated post-match
 * summaries (final score recap, scorers, cards, etc.).
 * Returns { [matchId]: { text, generatedAt } }.
 * Generated by /api/cron/sync-results when a match becomes FINISHED;
 * this endpoint only reads the cache. */
export async function GET() {
  try {
    const { db } = getAdmin();
    const snap = await db.collection("live_data").doc("match_summaries").get();
    return NextResponse.json(snap.exists ? (snap.data() || {}) : {});
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
