import { NextResponse } from "next/server";
import { getAdmin } from "@/lib/firebase-admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/* GET /api/match-previews — public cache of AI-generated match previews.
 * Returns { [matchId]: { text, generatedAt, matchUtc } }.
 * Generated by /api/cron/sync-match-previews; this endpoint only reads
 * the cache so it's cheap and doesn't call the AI. */
export async function GET() {
  try {
    const { db } = getAdmin();
    const snap = await db.collection("live_data").doc("match_previews").get();
    return NextResponse.json(snap.exists ? (snap.data() || {}) : {});
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
